### ISSUE TITLE
Make move stone and color order.

### ISSUE THREAD

**Issue by PeterVerzijl** [mmmcompany/QuirkleInterfaceRepository#1]
Hey, we forgot to set the representation of the colors and the shapes in the make move protocol. We should decide which char represents which color. I suggest this order:

| Char | Colors | SHAPES |
| --- | --- | --- |
| A | RED | CIRCLE |
| B | ORANGE | CROSS |
| C | YELLOW | DIAMOND |
| D | GREEN | SQUARE |
| E | BLUE | STAR |
| F | PRUPLE | PLUS |

Thus the syntax for setting a red cross on 1,-2 would then be:
MAKEMOVE_AB*1-2\n\n

**Comment by mmmcompany** [comment]
Implemented in version 1.2
