### ISSUE TITLE
Is leaderboard een totaalleaderboard per server of een lokaal leaderboard per game?

### ISSUE THREAD

**Issue by jonathanjuursema** [mmmcompany/QuirkleInterfaceRepository#11]
Volgens mij is dit in de protocolsessie besproken, maar ik kan het niet terugvinden in de docs.

**Comment by mmmcompany** [comment]
Leaderboard gaat per server,  dit is extra.
Het is wel verplicht om de scores door. Te geven op het einde van het spel

**Comment by jonathanjuursema** [comment]
Prima. :)
