### ISSUE TITLE
First move description wrong?

### ISSUE THREAD

**Issue by elborio** [mmmcompany/QuirkleInterfaceRepository#12]
Bij eerste beurt staat dat stap 2 is om iedereen individueel een beurt te geven,maar gaat dit geen errors opleveren ? Ten eerste is het niet nodig omdat als je een game start je gewoon iedereen de beurt kan laten hebben. Ten tweede staat MAKEMOVE_ _nextplayer_\n\n erg raar en word misschien op andere clients verkeerd geinterpreteerd.

**Comment by mmmcompany** [comment]
bij de protocol sessie is besproken om iedereen tegelijkertijd de beurt te geven.
Dit geeft enkel errors op het moment dat jij dat commando naar alle spelers broadcast.
Op het moment dat je client niet om kan gaan met het feit dat zijn move niet wordt neergelegd heb je ergens een verkeerde design keuze gemaakt. De server bepaald namelijk of een steen wordt neergelegd of niet met het MOVE commando.
Verde denk ik dat je nog even moet kijken naar het verschil tussen MOVE en MAKEMOVE dit zijn twee verschillende zaken.

mocht je nog problemen hebben kom ff langs.

**Comment by elborio** [comment]
Leek mij iig overbodig, verder lukt het prima:) 
Op 22 jan. 2016 15:06 schreef mmmcompany notifications@github.com:bij de protocol sessie is besproken om iedereen tegelijkertijd de beurt te geven.
Dit geeft enkel errors op het moment dat jij dat commando naar alle spelers broadcast.
Op het moment dat je client niet om kan gaan met het feit dat zijn move niet wordt neergelegd heb je ergens een verkeerde design keuze gemaakt. De server bepaald namelijk of een steen wordt neergelegd of niet met het MOVE commando.
Verde denk ik dat je nog even moet kijken naar het verschil tussen MOVE en MAKEMOVE dit zijn twee verschillende zaken.

mocht je nog problemen hebben kom ff langs.
