### ISSUE TITLE
Protocol.Server.GAME_END documentatie inconsistent

### ISSUE THREAD

**Issue by jonathanjuursema** [mmmcompany/QuirkleInterfaceRepository#13]
De GAME_END static geeft aan dat er een winner en een type kan resp. moet worden meegegeven, maar bij content staat niet op welke volgorde (END\n\n). Ik neem aan dat dit END_Type_WinnerOrMessage\n\n moet zijn?

**Comment by mmmcompany** [comment]
ik kan geen notulen terug vinden voor dit  specifieke scenario

Je mag jou implementatie opschrijven en een pull request aanmaken.

De GAME_END static geeft aan dat er een winner en een type kan resp. moet
worden meegegeven, maar bij content staat niet op welke volgorde (END\n\n).
Ik neem aan dat dit END_Type_WinnerOrMessage\n\n moet zijn?

—
Reply to this email directly or view it on GitHub
https://github.com/mmmcompany/QuirkleInterfaceRepository/issues/13.

**Comment by mmmcompany** [comment]
merged!
