### ISSUE TITLE
line separator

### ISSUE THREAD

**Issue by JerthG** [mmmcompany/QuirkleInterfaceRepository#3]
Hoi
Volgens mij is de standaard line separator in java "\n" en niet "\n\n" dus waarom zouden we die niet gebruiken. scheelt weer een hoop moeilijk doen...

jopen

Gerth

**Comment by PeterVerzijl** [comment]
It is actually system dependent, see the oracle documentation: [Java Doc](https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#lineSeparator%28%29)

> On UNIX systems, it returns "\n"; on Microsoft Windows systems it returns "\r\n".

**Comment by mmmcompany** [comment]
during the protocol session it was decided that this would be the carriage return.
based on Peter's comment i am not convinced yet that an edit ought to be made.
therefore this thread is now closed
