### ISSUE TITLE
Algemene error

### ISSUE THREAD

**Issue by StephanMB** [mmmcompany/QuirkleInterfaceRepository#5]
Zoals vandaag besproken in de practicum sessie; kunnen we een algemene Error toevoegen zodat andere errors die buiten de vastgelegde errors vallen gecontroleerd naar elkaar kunnen sturen.
Bijvoorbeeld met de syntax Error_Errormessage
Waarbij errormessage een string is met de melding erin.

**Comment by JerthG** [comment]
lijkt me handig, kan dit geimplementeerd worden?

**Comment by mmmcompany** [comment]
gaan we doen!
geimplementeerd in versie 1.3

**Comment by JerthG** [comment]
volgens mij was het de bedoeling dat er een aparte string voor een errormessage kwam, nu kun je alleen een message sturen achter die 7 errors die er zijn. is het niet handiger om dan een public final string ERRORMESSAGE oid te maken of een integer toe te wijzen bij deze error om ipv een vooraf gedefinieerde error gewoon een normale string te sturen zoals "he vriend, je hebt geen naam opgegeven bij je announce"

ohja, en bij de javadoc shizzle van ERROR in java mist een "/".

**Comment by mmmcompany** [comment]
Voor de belangerijkste errors hebben we een lijst met errors vastgesteld.
Voor de rest zul je het moeten doen met de general error.
Mochten er meer mensen zijn die hier een aanpassing willen doen dan moeten
deze dat ook aangeven op de issue en een voorgestelde implementatie zijn.

Op 18 januari 2016 17:18 schreef JasperGerth notifications@github.com:

**Comment by mmmcompany** [comment]
Er is nu een general error aangemaakt.
Deze heeft errorcode 8.
Verder is het ook mogelijk om nu een erroremessage mee te sturen.
Dit allemaal in versie 1.3.2
