### ISSUE TITLE
OKWAITFOR dubbelzinnig

### ISSUE THREAD

**Issue by RobinBol** [mmmcompany/QuirkleInterfaceRepository#6]
Het protocol zegt dat het commando: OKWAITFOR, een lijst met mensen terug geeft die zich op dat moment in de lobby bevinden. In de content staat echter OKWAITFOR_integer\n\n. Wat is nou het doel van dit commando? Het aantal mensen krijgen waarop moet worden gewacht voor een game kan starten, of de name/id van alle users in de lobby opvragen?

Als het om het aantal mensen gaat, moet er misschien nog een manier worden toegevoegd om de name/id van de spelers in de lobby op te vragen ivm het inviten (je wil weten wie je kunt uitnodigen).

```
Name: OKWAITFOR 
Descriptie: Een lijst met mensen die zich op het moment in de lobby bevinden. Wordt door de server     verstuurd bij Connect/Disconnect van een speler, en wanneer aangevraagd. 
Content: OKWAITFOR_integer\n\n
```

**Comment by mmmcompany** [comment]
Het doel van dit commando is inderdaaD op hoeveel mensen je nog moet wachten.

Het is correct dat we tijdens de protocol sessie het concept lobby hebben afgeschaft.
Gebruik van dit commando is in de javadoc gezet in versie 1.3

**Comment by RobinBol** [comment]
In het geval dat er geen lijst wordt gestuurd naar de client met namen om uit te kiezen; misschien verstandig om een error code toe te voegen (player does not exist)?

**Comment by mmmcompany** [comment]
Dit is onderdeel van de optionele challenge module.
Hier is nog geen implementatie voor bedacht.

Op 18 januari 2016 17:15 schreef Robin Bolscher notifications@github.com:
