### ISSUE TITLE
Omschrijving voor de eerste beurt lijkt te missen.

### ISSUE THREAD

**Issue by jonathanjuursema** [mmmcompany/QuirkleInterfaceRepository#7]
We hadden in de protocolsessie besloten hoe de eerste beurt er uit kwam te zien. Volgens mij was dat dat iedereen een zet deed, en daarna de zet met de langste waarde als eerste werd doorgevoerd. Kan dit nog in het protocol worden opgenomen?

**Comment by mmmcompany** [comment]
fixed in versie 1.3
