### ISSUE TITLE
Security?

### ISSUE THREAD

**Issue by RobinBol** [mmmcompany/QuirkleInterfaceRepository#8]
Tijdens de protocol sessie werd geopperd om een SSLSocket te gaan gebruiken voor security, is dit iets wat vanuit het protocol/door de groep moet worden geïmplementeerd/afgesproken?

**Comment by mmmcompany** [comment]
Ja dit is iets dat afgesproken moet worden.
Ik stel voor dat de eerste die een gedocumenteerde implementatie heeft een
voorstel mag doen qua implementatie en een pull request aanmaken op github.

Op 18 januari 2016 16:53 schreef Robin Bolscher notifications@github.com:

**Comment by RobinBol** [comment]
Niet zeker of het goed begrijp/implementeer, maar zal kort uitleggen hoe mijn huidige SSL implementatie werkt.

Heb een certificaat gegenereerd, die hebben de client en de server nodig om een versleutelde verbinding op zetten (als een client met een reguliere socket connect detecteer ik dat en switch ik naar een reguliere server socket). Voor zover ik weet, moet iedereen dus hetzelfde certificaat hebben, en die in de trustStore van de SSLServer zetten.

Correct me if i'm wrong.

**Comment by mmmcompany** [comment]
Tijdens de protocol sessie 2.1 op 19 januari  is besloten om ssl socket te kiezen voor secure communication.
het certificaat zal gemaakt worden door RobinBol.
Dit word meegeleverd met de volgende versie van het protocol
