### ISSUE TITLE
RE: Make move stone and color order.

### ISSUE THREAD

**Issue by roosalyn** [mmmcompany/QuirkleInterfaceRepository#9]
Bij de gesloten issues vroeg Peter naar de volgorde van de kleur en vorm enz. 
Dus nu is het: MAKEMOVE_AB*1-2\n\n
Maar moet er niet ook een delimiter tussen de twee integers? Als je nu een steen op plek 11,9 wil leggen zeg je dus: AB*119,dit kan dus ook op 11,9 zijn of 1,19 of hij crasht omdat hij uberhaupt maar één integer ziet (119).
Dus het voorstel is: MAKEMOVE_AB*1*-2/n/n ervan te maken. Voor de client én de server.

**Comment by mmmcompany** [comment]
Thanks!
gefixt in versie 1.3.2

**Comment by roosalyn** [comment]
Hey Martijn,
Je hebt het nu gedaan als: MOVE_AF_8_7maar ik bedoelde eigenlijk of het dit kon worden: MOVE_AF_8*7Ik dacht ook dat we dit hadden afgesproken tijdens de sessie en heb het ook zo geïmplementeerd.Ik weet niet wat de rest heeft gedaan maar het zou voor mij wel makkelijk zijn als het naar dat veranderd werd.

Date: Tue, 19 Jan 2016 05:29:11 -0800

**Comment by mmmcompany** [comment]
Hey Roosalyn,

Je hebt gelijk, in mijn notulen staat het met een underscore maar op meerdere foto's van het whiteboard staat inderdaad charchar_int_int.
aangepast in versie 1.3.4

**Comment by roosalyn** [comment]
Thanks!
